import Footer from "@/components/footer";
import "./globals.css";
import Header from "@/components/header/header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` font-mono bg-gray-50 flex flex-col min-h-screen`}
      >
        <Header />
        <main className="flex-1 mx-auto max-w-7xl w-full px-4 sm:px-6 lg:px-8 py-8">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
